#!/usr/bin/env bash
#MISE description="Build and push Docker image to registry"
#MISE depends=["docker:build"]

echo "Pushing Docker image $DOCKER_IMAGE..."
echo "  Latest: $DOCKER_IMAGE:latest"
echo "  Version: $DOCKER_IMAGE:$VERSION"
podman push $DOCKER_IMAGE:latest
podman push $DOCKER_IMAGE:$VERSION
echo "Docker images pushed successfully"
